server:
  port: 9002

spring:
  application:
    name: myshop-web
  datasource:
    url: jdbc:mysql://192.168.221.131:3306/springcloud?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能

management:
  health:
    db:
      enabled: false
